Update alarms.rst
uf-mil/mil pull request #1073
Opened 2023-08-28 21:22 UTC by MrinallU

## Description

## Screenshot or Video

## Related Issues

\- Closes #XXX

## Testing

## About This PR

- [ ] I have updated documentation related to this change so that future members are aware of the changes I've made.

2023-09-15 15:04 UTC, cbrxyz requested changes
Hi Mrinall! This is a good first attempt! The beginning and ends of this tutorial are great, and cover a great overview of why an alarm system has been implemented, and where someone can find more details about our specific implementation, `ros_alarms`.

Unfortunately, the documentation you write near the middle of the file is likely too unfocused for a `ros_alarms` introduction, as it focuses on general ROS services. You could consider moving some of your code into a separate tutorial about creating a ROS package with services and service files. However, inclusion of this material in documentation about a specific package like `ros_alarms` is too unfocused.

Apologies for the wait for a review, please make your corrections and submit when you have a chance, thank you!

2023-09-23 19:49 UTC, MrinallU commented
> Hi Mrinall! This is a good first attempt! The beginning and ends of this tutorial are great, and cover a great overview of why an alarm system has been implemented, and where someone can find more details about our specific implementation, `ros_alarms`.
> 
> Unfortunately, the documentation you write near the middle of the file is likely too unfocused for a `ros_alarms` introduction, as it focuses on general ROS services. You could consider moving some of your code into a separate tutorial about creating a ROS package with services and service files. However, inclusion of this material in documentation about a specific package like `ros_alarms` is too unfocused.
> 
> Apologies for the wait for a review, please make your corrections and submit when you have a chance, thank you!

Fixed! Thank you for the feedback!

2024-03-05 00:01 UTC, cbrxyz approved these changes
Thanks!
=

2024-03-05 00:17 UTC, cbrxyz approved these changes

2024-03-05 00:23 UTC, merged