python publisher for sdgps solution to hydrophone pings
uf-mil/mil pull request #1293
Opened 2024-10-20 01:54 UTC by alexoj46

## Description

This PR creates a bash script pipeline for posting the sdgps ping solution message over TCP (fakeping_pipeline.sh creates a fake ping for testing, and pipeline.sh receives real hydrophone pings).  Then, when running the python node ping_publisher.py, it will accept those TCP messages and publish them to the ROS node /ping for future use. These changes are part of the ROS package mil_passive_sonar.

## Screenshot or Video

<img width="1440" alt="Screenshot 2024-10-19 at 8 11 05 PM" src="https://github.com/user-attachments/assets/3b39584f-1a3f-41d0-a5e2-d2cf0c925128">
Each panel started in order: 
Bottom: Debug messages after running "rosrun mil_passive_sonar fakeping_pipeline.sh"
Upper left: Debug messages after running "rosrun mil_passive_sonar ping_publisher.py"
Upper right: Desired result of running "rostopic echo /ping"

## Related Issues

\- Closes #1288

## Testing

As shown in the image above, open three terminal windows (in tmux for ease of access). In one, run "rosrun mil_passive_sonar fakeping_pipeline.sh". In the next, run "rosrun mil_passive_sonar ping_publisher.py". In the final, use "rostopic echo /ping" to see the published ROS messages in the topic /ping.

I expect pipeline.sh to behave the same in place of fakeping_pipeline.sh, and intend to test with the boat at tomorrow's session.

## About This PR

- [ ] I have updated documentation related to this change so that future members are aware of the changes I've made.

2024-10-21 00:22 UTC, cbrxyz requested changes
Great job, alex!! Thank you for all your help! :)

2024-10-21 00:22 UTC, cbrxyz commented on mil_common/drivers/mil_passive_sonar/scripts/ping_publisher.py
I would try to name your branch something a little more descriptive! I generally follow this pattern:
```
<issue_number_if_exists>-<my_name>-<general_idea>
```

like:
* `1034-cameron-add-nodehandle-typing`
* `1254-cameron-add-ps4-controller-support`
* `cameron-fix-ufw-tables-zobelisk`

2024-10-21 00:22 UTC, cbrxyz commented on mil_common/drivers/mil_passive_sonar/scripts/ping_publisher.py
> +        print(f"Connected to {HOST}:{PORT}")
`rospy.loginfo`

2024-10-21 00:22 UTC, cbrxyz commented on mil_common/drivers/mil_passive_sonar/scripts/ping_publisher.py
> +        pub = rospy.Publisher("ping", ProcessedPing, queue_size=10)
I would name the topic related to "hydrophones", like "/hydrophones/solved", or "/hydrophones/locations"

2024-10-21 00:22 UTC, cbrxyz commented on mil_common/drivers/mil_passive_sonar/scripts/ping_publisher.py
> +        rospy.init_node("pingpublisher", anonymous=True)
I would put this before the call to `main`, near the bottom of the file. I know you probably don't know this yet, but that's where we usually declare `rospy` nodes! Just following that convention is helpful

2024-10-21 00:22 UTC, cbrxyz commented on mil_common/drivers/mil_passive_sonar/scripts/ping_publisher.py
> +                ping_msg.header.frame_id = "ping_frame"  # Set your frame_id
The [frame name should be `hydrophones`](https://github.com/uf-mil/mil/blob/master/NaviGator/simulation/navigator_gazebo/urdf/navigator.urdf.xacro#L25)

2024-10-21 00:22 UTC, cbrxyz commented on mil_common/drivers/mil_passive_sonar/scripts/ping_publisher.py
> +                ]  # You can modify this as needed
You can probably remove the comment here

2024-10-21 00:22 UTC, cbrxyz commented on mil_common/drivers/mil_passive_sonar/scripts/ping_publisher.py
> +                ]  # You can modify this as needed
will probably help with the weird bracket autoformatting goin on here

2024-10-21 00:22 UTC, cbrxyz commented on mil_common/drivers/mil_passive_sonar/scripts/ping_publisher.py
> +                rospy.loginfo(f"Published: {ping_msg}")
No need to log each time a new ping is published

2024-10-21 00:22 UTC, cbrxyz commented on mil_common/drivers/mil_passive_sonar/scripts/ping_publisher.py
> +                rospy.loginfo(f"JSON Decode Error: {e}")
I would use `logerr` here, since we definitely want to be notified when this happens!

2024-10-21 00:22 UTC, cbrxyz commented on mil_common/drivers/mil_passive_sonar/scripts/ping_publisher.py
> +                rospy.loginfo(f"Key Error: {e}")
Same here (`logerr`)

2024-10-21 00:22 UTC, cbrxyz commented on mil_common/drivers/mil_passive_sonar/src/pipeline.sh
> +sdgps connect-sonar-raw-tcp --host 192.168.37.51 --port 2006 ! filter-sonar-raw-samples --highpass 15e3 --lowpass 45e3 --notch 40e3 ! extract-robosub-pings ! robosub-ping-solver ! listen-robosub-ping
Sorry! I made a mistake here! [The IP should end wth 61, not 51](https://mil.ufl.edu/docs/infrastructure/network.html#allocation-table).

2024-10-21 00:22 UTC, cbrxyz commented on mil_common/drivers/mil_passive_sonar/scripts/ping_publisher.py
for this PR though, it's totally fine! Just for the future

2024-10-28 00:20 UTC, alexoj46 commented
This week, I made and committed the requested changes to my PR above, and cleaned up some error handling for the hydrophone publisher. I also attended today's testing session.

2024-10-28 02:44 UTC, cbrxyz commented
Rebased to remove the broken `pre-commit.ci` check (#1298)

2024-10-28 02:48 UTC, cbrxyz approved these changes
Thanks Alex!

2024-10-28 03:02 UTC, merged