p3d to sylphase for indyav urdf
uf-mil/mil pull request #250
Opened 2020-09-10 18:05 UTC by alexperez33

added sylphase and fixed_link_persistent xacros to xacro folder as they are required to add sylphase to indyav urdf. deleted p3d xacro instance and include, and added the same sylphase instance as from the navigator urdf

2020-09-10 19:24 UTC, MarshallRawson requested changes
Leave a comment describing how to demonstrate the changes made

2020-09-10 19:24 UTC, MarshallRawson commented on IndyAV/simulation/indyav_gazebo/xacro/fixed_link_persistent.xacro
> +<?xml version="1.0"?>
This file shouldnt be included as it is a copy of the one in Navigator.

2020-09-10 19:24 UTC, MarshallRawson commented on IndyAV/simulation/indyav_gazebo/xacro/sylphase.xacro
> +<?xml version="1.0"?>
This file is a copy of the one in Navigator

2020-09-11 00:17 UTC, alexperez33 commented
roslaunch indyav_launch gazebo.launch
rostopic list //shows the topic "ins_odom"
rostopic echo /ins_odom //shows the topics info successfully

2020-09-11 00:21 UTC, MarshallRawson commented
> roslaunch indyav_launch gazebo.launch
> rostopic list //shows the topic "ins_odom"
> rostopic echo /ins_odom //shows the topics info successfully

pro tip:
git hub comments are in markdown!

`roslaunch indyav_launch gazebo.launch`
`rostopic list #shows the topic ins_odom`
`rostopic echo #ins_odom //shows the topics info successfully`

2020-09-11 00:37 UTC, MarshallRawson commented
> roslaunch indyav_launch gazebo.launch
> rostopic list //shows the topic "ins_odom"
> rostopic echo /ins_odom //shows the topics info successfully

Great! Also, could you write a ros test and put it under the `IndyAV/localization/test` directory. Also, go and update the documentation under `docs/indyav/software/simulation/gazebo/gazebo.dot` and change the p3d to syphaze Also, update the `docs/indyav/software/localization.rst` to say that we are currently using the Sylphase INS

2020-09-11 22:08 UTC, alexperez33 commented
To demo the change,
`roslaunch indyav_launch gazebo.launch`
Then in another terminal
`cd ~/mil_ws/src/mil/IndyAV/localization/indyav_localization/test`
`./test_sylphase.py`

2020-09-17 19:18 UTC, MarshallRawson commented
the test is failing because the ros node in the test is being re-initialized on like 19

2020-09-17 19:18 UTC, MarshallRawson requested changes

2020-09-17 19:18 UTC, MarshallRawson commented on IndyAV/command/indyav_launch/launch/odometry.launch
> +  <!-- This file is no longer being run -->
delete this commented out node from this launch file

2020-09-17 19:18 UTC, MarshallRawson commented on IndyAV/localization/indyav_localization/test/test_sylphase.py
> +        sleep(8) #allows ample time for sim to start up
replace with `rospy.wait_for_service("/gazebo/spawn_urdf_model")`

2020-09-17 19:18 UTC, MarshallRawson commented on IndyAV/localization/indyav_localization/test/test_sylphase.py
> +        rospy.init_node('test_sylphase')
remove this line as this tis taken care of on line 40

2020-09-17 19:18 UTC, MarshallRawson commented on IndyAV/simulation/indyav_gazebo/urdf/indyav_car.urdf.xacro
> +  <!-- <xacro:property name="namespace" value="indyav_car"/> -->
delete these two commented out properties

2020-09-18 16:28 UTC, MarshallRawson approved these changes

2020-09-18 16:28 UTC, merged