Added network kill
uf-mil/mil pull request #856
Opened 2022-08-29 18:42 UTC by andrew-aj

Closes #854

2022-08-29 22:53 UTC, kawaiiPlat approved these changes
ye

2022-08-29 23:11 UTC, kawaiiPlat requested changes
Gives a timeout during unit testing.

2022-09-03 22:53 UTC, cbrxyz commented on NaviGator/hardware_drivers/navigator_kill_board/nodes/kill_board_driver.py
> +        # )  # Passes along network hearbeat to kill board
This should be removed or a comment should be added explaining why this is commented out.

2022-09-03 22:53 UTC, cbrxyz commented on NaviGator/hardware_drivers/navigator_kill_board/nodes/kill_board_driver.py
> +        self.ser.write(bytes(write_str, "utf-8"))
22f3d47 needs to be merged in to this branch.

2022-09-03 22:53 UTC, cbrxyz commented on NaviGator/hardware_drivers/navigator_kill_board/nodes/kill_board_driver.py
> +            if self.sw_killed:
Unless I'm missing something, we could maybe expand `nw_killed` and `sw_killed` to their full name. I'm having a hard time understanding what the "nw" and "sw" mean.

2022-09-03 22:53 UTC, cbrxyz commented on NaviGator/hardware_drivers/navigator_kill_board/test/kill_board_test_4.py
> +        # self.heartbeat = HeartbeatServer("/network", 1.0)
Why is this commented out?

2022-09-03 22:53 UTC, cbrxyz commented on NaviGator/hardware_drivers/navigator_kill_board/test/kill_board_test_4.py
> +        # self.heartbeat = HeartbeatServer("/network", 0.5)
Same

2022-09-04 02:57 UTC, cbrxyz approved these changes
Looks good, thanks!

2022-09-04 02:57 UTC, merged